package main

// On Windows we install the daemon by dropping a VBScript launcher into
// the per-user Startup folder
// (%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup\). Windows runs
// every script in that folder at user logon, in the user's session, with
// full access to their credential vault and SSH keys, and without
// requiring admin rights.
//
// We use a .vbs (not a .cmd) deliberately. A .cmd launched at logon opens
// a cmd.exe console; if the script then runs the daemon with
// `start "" /B`, the daemon inherits that console and the window stays
// open as long as the daemon runs. WScript.Shell.Run with window-style 0
// and bWaitOnReturn=False launches the daemon truly hidden and detached,
// and wscript.exe exits immediately.
//
// We deliberately do NOT use Task Scheduler — schtasks.exe /Create requires
// admin (Microsoft's rule, regardless of /RL LIMITED), which would force
// users to elevate every time they install or change the daemon.
//
// Lifecycle (start/stop/status) is managed via a PID file written by the
// daemon itself at ~/.claudesync/daemon.pid.

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"syscall"

	"github.com/MarimerLLC/claude-utils/internal/proc"
)

// detachedSysProcAttr returns SysProcAttr that detaches the spawned
// process from the parent console and gives it its own process group, so
// the daemon outlives our CLI invocation cleanly.
func detachedSysProcAttr() *syscall.SysProcAttr {
	return &syscall.SysProcAttr{
		HideWindow:    true,
		CreationFlags: 0x00000008 | 0x00000200, // DETACHED_PROCESS | CREATE_NEW_PROCESS_GROUP
	}
}

// startupFolder returns the per-user Startup folder.
func startupFolder() (string, error) {
	appdata := os.Getenv("APPDATA")
	if appdata == "" {
		return "", fmt.Errorf("APPDATA not set")
	}
	return filepath.Join(appdata, "Microsoft", "Windows", "Start Menu", "Programs", "Startup"), nil
}

// startupScriptPath returns the absolute path to the .vbs launcher in the
// user's Startup folder.
func startupScriptPath() (string, error) {
	dir, err := startupFolder()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "claude-memsync.vbs"), nil
}

// legacyStartupScriptPath returns the path to the pre-0.x .cmd launcher
// that earlier installs dropped into the Startup folder. We remove it on
// install/uninstall so users who upgrade don't end up with both.
func legacyStartupScriptPath() (string, error) {
	dir, err := startupFolder()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "claude-memsync.cmd"), nil
}

// vbsQuote escapes a string for inclusion inside a VBScript double-quoted
// literal. In VBScript, a double quote is escaped by doubling it.
func vbsQuote(s string) string {
	return strings.ReplaceAll(s, `"`, `""`)
}

func installTask(configPath string) error {
	exe, err := os.Executable()
	if err != nil {
		return fmt.Errorf("locate executable: %w", err)
	}
	scriptPath, err := startupScriptPath()
	if err != nil {
		return err
	}
	// Build the command line that WScript.Shell.Run will execute. The
	// outer literal is a VBScript double-quoted string, so any embedded
	// double quotes must be doubled.
	cmd := fmt.Sprintf(`"%s" run`, exe)
	if configPath != "" && configPath != defaultConfigPath() {
		cmd = fmt.Sprintf(`"%s" run --config "%s"`, exe, configPath)
	}
	body := "' auto-generated by claude-memsync install; do not edit by hand\r\n" +
		"' window style 0 = hidden, bWaitOnReturn = False = fire-and-forget\r\n" +
		"CreateObject(\"WScript.Shell\").Run \"" + vbsQuote(cmd) + "\", 0, False\r\n"
	if err := os.MkdirAll(filepath.Dir(scriptPath), 0700); err != nil {
		return err
	}
	if err := os.WriteFile(scriptPath, []byte(body), 0600); err != nil {
		return fmt.Errorf("write startup script %s: %w", scriptPath, err)
	}
	// Best-effort removal of the pre-vbs .cmd launcher so users upgrading
	// from an older version don't get both at next logon.
	if legacy, err := legacyStartupScriptPath(); err == nil {
		_ = os.Remove(legacy)
	}
	return nil
}

func uninstallTask() error {
	scriptPath, err := startupScriptPath()
	if err != nil {
		return err
	}
	var firstErr error
	if err := os.Remove(scriptPath); err != nil && !os.IsNotExist(err) {
		firstErr = fmt.Errorf("remove startup script %s: %w", scriptPath, err)
	}
	if legacy, err := legacyStartupScriptPath(); err == nil {
		if err := os.Remove(legacy); err != nil && !os.IsNotExist(err) && firstErr == nil {
			firstErr = fmt.Errorf("remove legacy startup script %s: %w", legacy, err)
		}
	}
	return firstErr
}

func startTask() error {
	if pid, _ := readPidFile(); pid > 0 && processAlive(pid) {
		return fmt.Errorf("already running (pid %d)", pid)
	}
	exe, err := os.Executable()
	if err != nil {
		return fmt.Errorf("locate executable: %w", err)
	}
	// Spawn detached so the daemon outlives this CLI invocation.
	c := exec.Command(exe, "run")
	c.SysProcAttr = detachedSysProcAttr()
	c.Stdout = nil
	c.Stderr = nil
	c.Stdin = nil
	if err := c.Start(); err != nil {
		return fmt.Errorf("start daemon: %w", err)
	}
	// Don't Wait() — let it run in the background.
	_ = c.Process.Release()
	return nil
}

func stopTask() error {
	pid, err := readPidFile()
	if err != nil || pid <= 0 {
		return fmt.Errorf("not running (no pid file)")
	}
	p, err := os.FindProcess(pid)
	if err != nil {
		return fmt.Errorf("find pid %d: %w", pid, err)
	}
	if err := p.Kill(); err != nil {
		return fmt.Errorf("kill pid %d: %w", pid, err)
	}
	_ = removePidFile()
	return nil
}

func statusTask() (string, error) {
	pid, err := readPidFile()
	if err != nil || pid <= 0 {
		return "stopped", nil
	}
	if !processAlive(pid) {
		_ = removePidFile()
		return "stopped", nil
	}
	return fmt.Sprintf("running (pid %d)", pid), nil
}

// processAlive returns true if the process with the given pid exists. On
// Windows os.FindProcess always succeeds, so we probe via `tasklist` to
// keep the implementation small and avoid pulling in golang.org/x/sys.
func processAlive(pid int) bool {
	cmd := exec.Command("tasklist", "/FI", fmt.Sprintf("PID eq %d", pid), "/NH", "/FO", "CSV")
	proc.HideWindow(cmd)
	out, err := cmd.Output()
	if err != nil {
		return false
	}
	return strings.Contains(string(out), strconv.Itoa(pid))
}
